
import Bar from 'components/Bar'
import Gauge from 'components/Gauge'
import MultipleLine from 'components/MultipleLine'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bar />
      <MultipleLine/>
      <Gauge/>

    </div>
  )
}

export default Home
